# Generated by Django 5.2 on 2025-04-02 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('mesas', '0001_initial'),
        ('meseros', '0001_initial'),
        ('platos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10)),
                ('fechaHora', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('mesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mesas.mesa')),
                ('mesero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meseros.mesero')),
                ('platos', models.ManyToManyField(to='platos.plato')),
            ],
        ),
    ]
